### ISSUE TITLE
FPS Overlay option

### ISSUE THREAD

**Issue by NikoofDeath** [teakhanirons/lolita500#1]
The one feature from LOLIcon that is missing from this plugin (which is much preferable for VitaTV) is the FPS overlay option, which I prefer to framecounter due to its transparent background. Would it be possible for this to be implemented in LOLITA500?

**Comment by teakhanirons** [comment]
I seperated the overlay features to another plugin called DerInClocKS. It'd
be trivial to implement it to that. If you don't think you have the skill
to do so yourself, tell me and I'll take a look.

2 Ara 2019 Pzt 05:21 tarihinde NikoofDeath <notifications@github.com> şunu
yazdı:

**Comment by teakhanirons** [comment]
Been two weeks, closing it.
